### ISSUE TITLE
add "allocate/free the universe" test

### ISSUE THREAD

**Issue by duckinator** [awooos/dmm#9]
rough idea:

```c
size_t dmm_available_memory()
{
    return /* TODO */;
}

size_t test_dmm_allocate_world()
{
    TEST_HAS_ASSERTIONS();

    size_t world_size;
    size_t world_size2;

    void *world;
    void *world2;

    world_size = dmm_available_memory();
    TEST_ASSERT(world_size > 0);

    world = dmm_malloc(world_size);
    TEST_ASSERT(world != NULL);
    TEST_ASSERT(dmm_available_memory() == 0); // TODO: Probably need to add margin of error?

    dmm_free(world);

    world_size2 = dmm_available_memory();
    TEST_ASSERT(world_size2 == world_size); // TODO: Probably need to add margin of error?
    TEST_ASSERT(world_size2 > 0);

    world2 = dmm_malloc(world_size);
    TEST_ASSERT(world != NULL);
    TEST_ASSERT(dmm_available_memory() == 0); // TODO: Probably need to add margin of error?

    dmm_free(world);

    TEST_ASSERT(world_size2 == dmm_available_memory()); // TODO: Probably need to add margin of error?
    TEST_ASSERT(dmm_available_memory() > 0);

    TEST_ASSERTIONS_RETURN();
}
```

**Comment by 0x52a1** [comment]
the problem with the example given is that "available memory" isn't "amount of memory that can be allocated in one chunk" due to the fact that it's split up across memory regions (for example, the allocator knows about and can allocate memory below 1M, and then there's the kernel memory space, and then more allocatable memory). 

a potentially better idea is to allocate as many 1K chunks as possible until the memory manager returns null pointers, loop through the chunk headers checking everything is correct, freeing everything, and repeating - although, this wouldn't work until dmm's `free()` actually merges free regions together rather than just setting the free flag in the chunk header

**Comment by duckinator** [comment]
yeah, I agree, that's definitely a better way to approach it.
